name: Build LiteX & software binary
on:
  [push, pull_request, workflow_dispatch]

jobs:
  build-litex:
    runs-on: ubuntu-20.04

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install required packages
      run: |
        sudo apt-get -qq -y update
        sudo apt-get -qq -y install python3-setuptools python3-pip make libevent-dev libjson-c-dev build-essential libtinfo-dev wget bzip2 ninja-build

    - name: Install Python dependencies
      run: |
        sudo pip3 install meson

    - name: Setup environment
      run: |
        ./scripts/install.sh

    - name: Build LiteX software
      run: |
        source ./scripts/init
        make litex-software

  build-software:
    runs-on: ubuntu-20.04

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        wget https://apt.kitware.com/kitware-archive.sh
        sudo bash kitware-archive.sh
        sudo apt install --no-install-recommends git cmake ninja-build gperf ccache dfu-util device-tree-compiler wget python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev
        cmake --version
        python3 --version
        dtc --version

    - name: Install Zephyr toolchain
      run: |
        wget --progress=dot:giga https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.13.2/zephyr-sdk-0.13.2-linux-x86_64-setup.run
        chmod +x zephyr-sdk-0.13.2-linux-x86_64-setup.run
        ./zephyr-sdk-0.13.2-linux-x86_64-setup.run -- -d ~/zephyr-sdk-0.13.2

    - name: Initialize Zephyr and install Python dependencies
      run: |
        pip3 install --user -U west
        export PATH=~/.local/bin:"$PATH"
        make setup-zephyr
        pip3 install --user -r software/zephyr/scripts/requirements.txt

    - name: Build application
      run: |
        make software

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: app-binaries
        path: |
          software/video-overlays-zephyr-app/build/zephyr/zephyr.bin
          software/video-overlays-zephyr-app/build/zephyr/zephyr.elf
